baseURL = 'https://koalaquakes.github.io/'
languageCode = 'en-us'
title = 'My Blog Project'
theme = "LoveIt"

[params]
  defaultTheme = "dark"
  description = "DevOps, CI/CD and infrastructure tutorials"

[params.home.profile]
  enable = true
  avatarURL = "/images/avatar.png"
  title = "Shane Hart"
  subtitle = "DevOps | Automation | Infrastructure"
